// Fake Data for Curriculum V2 System
import { CurriculumnSubjectModel } from "../model/CurriculumnSubjectModel";

// Curriculum Info
export const FakeCurriculumInfo = {
  id: "curriculum-1704067200000",
  name: "Computer Science Bachelor Program 2024",
  description:
    "Comprehensive 4-year bachelor program in Computer Science with focus on software development, data structures, algorithms, and emerging technologies.",
  academicYear: "2024",
  facultyId: "1",
  majorId: "1",
  totalCredits: 140,
  createdAt: "2024-01-01T00:00:00.000Z",
};

// Board Types Configuration
export const FakeBoardTypes = [
  {
    id: "core",
    name: "Core Subjects",
    description: "Essential subjects that all students must complete",
    type: "core",
    color: "bg-blue-500",
    defaultSemesters: 8,
  },
  {
    id: "physical_education",
    name: "Physical Education",
    description: "Physical fitness and sports-related courses",
    type: "physical_education",
    color: "bg-green-500",
    defaultSemesters: 2,
  },
  {
    id: "skill_development",
    name: "Skill Development",
    description: "Practical skills and soft skills training",
    type: "skill_development",
    color: "bg-purple-500",
    defaultSemesters: 4,
  },
  {
    id: "english",
    name: "English Courses",
    description: "Language proficiency and communication skills",
    type: "english",
    color: "bg-orange-500",
    defaultSemesters: 3,
  },
  {
    id: "philosophy",
    name: "Philosophy & Ethics",
    description: "Philosophical thinking and ethical reasoning",
    type: "philosophy",
    color: "bg-red-500",
    defaultSemesters: 2,
  },
];

// Board Structures
export const FakeBoards = [
  // Core Subjects Board (8 semesters)
  {
    id: "board-core-1704067200000-0",
    name: "Core Subjects",
    type: "core",
    curriculumId: "curriculum-1704067200000",
    curriculumTypeId: "curriculum-type-core-1704067200000",
    columnOrder: [
      "semester-1-board-core-1704067200000-0",
      "semester-2-board-core-1704067200000-0",
      "semester-3-board-core-1704067200000-0",
      "semester-4-board-core-1704067200000-0",
      "semester-5-board-core-1704067200000-0",
      "semester-6-board-core-1704067200000-0",
      "semester-7-board-core-1704067200000-0",
      "semester-8-board-core-1704067200000-0",
    ],
    semesterColumn: {
      "semester-1-board-core-1704067200000-0": {
        id: "semester-1-board-core-1704067200000-0",
        title: "Semester 1",
        subjectIds: [
          "subject-101-1704067200001-abc123def",
          "subject-102-1704067200002-def456ghi",
          "subject-103-1704067200003-ghi789jkl",
          "subject-104-1704067200004-jkl012mno",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 1,
      },
      "semester-2-board-core-1704067200000-0": {
        id: "semester-2-board-core-1704067200000-0",
        title: "Semester 2",
        subjectIds: [
          "subject-201-1704067200005-mno345pqr",
          "subject-202-1704067200006-pqr678stu",
          "subject-203-1704067200007-stu901vwx",
          "subject-204-1704067200008-vwx234yza",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 2,
      },
      "semester-3-board-core-1704067200000-0": {
        id: "semester-3-board-core-1704067200000-0",
        title: "Semester 3",
        subjectIds: [
          "subject-301-1704067200009-yza567bcd",
          "subject-302-1704067200010-bcd890efg",
          "subject-303-1704067200011-efg123hij",
          "subject-304-1704067200012-hij456klm",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 3,
      },
      "semester-4-board-core-1704067200000-0": {
        id: "semester-4-board-core-1704067200000-0",
        title: "Semester 4",
        subjectIds: [
          "subject-401-1704067200013-klm789nop",
          "subject-402-1704067200014-nop012qrs",
          "subject-403-1704067200015-qrs345tuv",
          "subject-404-1704067200016-tuv678wxy",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 4,
      },
      "semester-5-board-core-1704067200000-0": {
        id: "semester-5-board-core-1704067200000-0",
        title: "Semester 5",
        subjectIds: [
          "subject-501-1704067200017-wxy901zab",
          "subject-502-1704067200018-zab234cde",
          "subject-503-1704067200019-cde567fgh",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 5,
      },
      "semester-6-board-core-1704067200000-0": {
        id: "semester-6-board-core-1704067200000-0",
        title: "Semester 6",
        subjectIds: [
          "subject-601-1704067200020-fgh890ijk",
          "subject-602-1704067200021-ijk123lmn",
          "subject-603-1704067200022-lmn456opq",
        ],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 6,
      },
      "semester-7-board-core-1704067200000-0": {
        id: "semester-7-board-core-1704067200000-0",
        title: "Semester 7",
        subjectIds: ["subject-701-1704067200023-opq789rst", "subject-702-1704067200024-rst012uvw"],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 7,
      },
      "semester-8-board-core-1704067200000-0": {
        id: "semester-8-board-core-1704067200000-0",
        title: "Semester 8",
        subjectIds: ["subject-801-1704067200025-uvw345xyz", "subject-802-1704067200026-xyz678abc"],
        curriculumTypeId: "curriculum-type-core-1704067200000",
        semesterNumber: 8,
      },
    },
  },
  // Physical Education Board (2 semesters)
  {
    id: "board-physical_education-1704067200000-1",
    name: "Physical Education",
    type: "physical_education",
    curriculumId: "curriculum-1704067200000",
    curriculumTypeId: "curriculum-type-physical_education-1704067200000",
    columnOrder: [
      "semester-1-board-physical_education-1704067200000-1",
      "semester-2-board-physical_education-1704067200000-1",
    ],
    semesterColumn: {
      "semester-1-board-physical_education-1704067200000-1": {
        id: "semester-1-board-physical_education-1704067200000-1",
        title: "Physical Education 1",
        subjectIds: ["subject-pe101-1704067200027-def901ghi"],
        curriculumTypeId: "curriculum-type-physical_education-1704067200000",
        semesterNumber: 1,
      },
      "semester-2-board-physical_education-1704067200000-1": {
        id: "semester-2-board-physical_education-1704067200000-1",
        title: "Physical Education 2",
        subjectIds: ["subject-pe201-1704067200028-ghi234jkl"],
        curriculumTypeId: "curriculum-type-physical_education-1704067200000",
        semesterNumber: 2,
      },
    },
  },
  // English Courses Board (3 semesters)
  {
    id: "board-english-1704067200000-2",
    name: "English Courses",
    type: "english",
    curriculumId: "curriculum-1704067200000",
    curriculumTypeId: "curriculum-type-english-1704067200000",
    columnOrder: [
      "semester-1-board-english-1704067200000-2",
      "semester-2-board-english-1704067200000-2",
      "semester-3-board-english-1704067200000-2",
    ],
    semesterColumn: {
      "semester-1-board-english-1704067200000-2": {
        id: "semester-1-board-english-1704067200000-2",
        title: "English Courses 1",
        subjectIds: ["subject-eng101-1704067200029-jkl567mno"],
        curriculumTypeId: "curriculum-type-english-1704067200000",
        semesterNumber: 1,
      },
      "semester-2-board-english-1704067200000-2": {
        id: "semester-2-board-english-1704067200000-2",
        title: "English Courses 2",
        subjectIds: ["subject-eng201-1704067200030-mno890pqr"],
        curriculumTypeId: "curriculum-type-english-1704067200000",
        semesterNumber: 2,
      },
      "semester-3-board-english-1704067200000-2": {
        id: "semester-3-board-english-1704067200000-2",
        title: "English Courses 3",
        subjectIds: ["subject-eng301-1704067200031-pqr123stu"],
        curriculumTypeId: "curriculum-type-english-1704067200000",
        semesterNumber: 3,
      },
    },
  },
];

// Subject Data in New Format
export const FakeCurriculumSubjects: { [key: string]: CurriculumnSubjectModel } = {
  // Core Subjects - Semester 1
  "subject-101-1704067200001-abc123def": {
    SubjectID: "101",
    SubjectName: "Calculus I",
    SubjectName_EN: "Calculus I",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 4,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 1",
    PrerequisiteSubjects: [],
  },
  "subject-102-1704067200002-def456ghi": {
    SubjectID: "102",
    SubjectName: "Introduction to Programming",
    SubjectName_EN: "Introduction to Programming",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 1",
    PrerequisiteSubjects: [],
  },
  "subject-103-1704067200003-ghi789jkl": {
    SubjectID: "103",
    SubjectName: "Physics I",
    SubjectName_EN: "Physics I",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 1",
    PrerequisiteSubjects: [],
  },
  "subject-104-1704067200004-jkl012mno": {
    SubjectID: "104",
    SubjectName: "Linear Algebra",
    SubjectName_EN: "Linear Algebra",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 1",
    PrerequisiteSubjects: [],
  },

  // Core Subjects - Semester 2
  "subject-201-1704067200005-mno345pqr": {
    SubjectID: "201",
    SubjectName: "Calculus II",
    SubjectName_EN: "Calculus II",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 4,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 2",
    PrerequisiteSubjects: [
      {
        id: "101",
        name: "Calculus I",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Fundamental calculus concepts",
      },
    ],
  },
  "subject-202-1704067200006-pqr678stu": {
    SubjectID: "202",
    SubjectName: "Object-Oriented Programming",
    SubjectName_EN: "Object-Oriented Programming",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 2",
    PrerequisiteSubjects: [
      {
        id: "102",
        name: "Introduction to Programming",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Basic programming concepts",
      },
    ],
  },
  "subject-203-1704067200007-stu901vwx": {
    SubjectID: "203",
    SubjectName: "Physics II",
    SubjectName_EN: "Physics II",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 2",
    PrerequisiteSubjects: [
      {
        id: "103",
        name: "Physics I",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Basic physics principles",
      },
    ],
  },
  "subject-204-1704067200008-vwx234yza": {
    SubjectID: "204",
    SubjectName: "Discrete Mathematics",
    SubjectName_EN: "Discrete Mathematics",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 2",
    PrerequisiteSubjects: [],
  },

  // Core Subjects - Semester 3
  "subject-301-1704067200009-yza567bcd": {
    SubjectID: "301",
    SubjectName: "Data Structures and Algorithms",
    SubjectName_EN: "Data Structures and Algorithms",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 3,
    SemesterColumnId: 3,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 3",
    PrerequisiteSubjects: [
      {
        id: "202",
        name: "Object-Oriented Programming",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "OOP concepts and implementation",
      },
    ],
  },
  "subject-302-1704067200010-bcd890efg": {
    SubjectID: "302",
    SubjectName: "Database Systems",
    SubjectName_EN: "Database Systems",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 3,
    SemesterColumnId: 3,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 3",
    PrerequisiteSubjects: [],
  },
  "subject-303-1704067200011-efg123hij": {
    SubjectID: "303",
    SubjectName: "Computer Architecture",
    SubjectName_EN: "Computer Architecture",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 3,
    SemesterColumnId: 3,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 3",
    PrerequisiteSubjects: [],
  },
  "subject-304-1704067200012-hij456klm": {
    SubjectID: "304",
    SubjectName: "Statistics and Probability",
    SubjectName_EN: "Statistics and Probability",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 3,
    SemesterColumnId: 3,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 3",
    PrerequisiteSubjects: [
      {
        id: "201",
        name: "Calculus II",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Advanced calculus concepts",
      },
    ],
  },

  // Core Subjects - Semester 4
  "subject-401-1704067200013-klm789nop": {
    SubjectID: "401",
    SubjectName: "Operating Systems",
    SubjectName_EN: "Operating Systems",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 4,
    SemesterColumnId: 4,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 4",
    PrerequisiteSubjects: [
      {
        id: "301",
        name: "Data Structures and Algorithms",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Data structures and algorithmic thinking",
      },
    ],
  },
  "subject-402-1704067200014-nop012qrs": {
    SubjectID: "402",
    SubjectName: "Computer Networks",
    SubjectName_EN: "Computer Networks",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 4,
    SemesterColumnId: 4,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 4",
    PrerequisiteSubjects: [],
  },
  "subject-403-1704067200015-qrs345tuv": {
    SubjectID: "403",
    SubjectName: "Software Engineering",
    SubjectName_EN: "Software Engineering",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 4,
    SemesterColumnId: 4,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 4",
    PrerequisiteSubjects: [
      {
        id: "202",
        name: "Object-Oriented Programming",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "OOP concepts and implementation",
      },
    ],
  },
  "subject-404-1704067200016-tuv678wxy": {
    SubjectID: "404",
    SubjectName: "Web Development",
    SubjectName_EN: "Web Development",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 4,
    SemesterColumnId: 4,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 2,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 4",
    PrerequisiteSubjects: [
      {
        id: "202",
        name: "Object-Oriented Programming",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "OOP concepts and implementation",
      },
    ],
  },

  // Core Subjects - Semester 5 (Advanced Topics)
  "subject-501-1704067200017-wxy901zab": {
    SubjectID: "501",
    SubjectName: "Artificial Intelligence",
    SubjectName_EN: "Artificial Intelligence",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 5,
    SemesterColumnId: 5,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 2,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 2,
    SemesterName: "Semester 5",
    PrerequisiteSubjects: [
      {
        id: "301",
        name: "Data Structures and Algorithms",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Data structures and algorithmic thinking",
      },
      {
        id: "304",
        name: "Statistics and Probability",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Statistical analysis and probability theory",
      },
    ],
  },
  "subject-502-1704067200018-zab234cde": {
    SubjectID: "502",
    SubjectName: "Machine Learning",
    SubjectName_EN: "Machine Learning",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 5,
    SemesterColumnId: 5,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 2,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 2,
    SemesterName: "Semester 5",
    PrerequisiteSubjects: [
      {
        id: "501",
        name: "Artificial Intelligence",
        credits: 4,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "AI fundamentals and algorithms",
      },
      {
        id: "304",
        name: "Statistics and Probability",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Statistical analysis and probability theory",
      },
    ],
  },
  "subject-503-1704067200019-cde567fgh": {
    SubjectID: "503",
    SubjectName: "Cybersecurity",
    SubjectName_EN: "Cybersecurity",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 5,
    SemesterColumnId: 5,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 5",
    PrerequisiteSubjects: [
      {
        id: "402",
        name: "Computer Networks",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Network protocols and architectures",
      },
    ],
  },

  // Core Subjects - Semester 6
  "subject-601-1704067200020-fgh890ijk": {
    SubjectID: "601",
    SubjectName: "Mobile Application Development",
    SubjectName_EN: "Mobile Application Development",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 6,
    SemesterColumnId: 6,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 2,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 6",
    PrerequisiteSubjects: [
      {
        id: "404",
        name: "Web Development",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Web development fundamentals",
      },
    ],
  },
  "subject-602-1704067200021-ijk123lmn": {
    SubjectID: "602",
    SubjectName: "Cloud Computing",
    SubjectName_EN: "Cloud Computing",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 6,
    SemesterColumnId: 6,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 6",
    PrerequisiteSubjects: [
      {
        id: "402",
        name: "Computer Networks",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Network protocols and architectures",
      },
    ],
  },
  "subject-603-1704067200022-lmn456opq": {
    SubjectID: "603",
    SubjectName: "Data Mining",
    SubjectName_EN: "Data Mining",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 6,
    SemesterColumnId: 6,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 6",
    PrerequisiteSubjects: [
      {
        id: "302",
        name: "Database Systems",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Database design and management",
      },
    ],
  },

  // Core Subjects - Semester 7 (Project-focused)
  "subject-701-1704067200023-opq789rst": {
    SubjectID: "701",
    SubjectName: "Capstone Project I",
    SubjectName_EN: "Capstone Project I",
    TotalCredits: 6,
    MajorID: "1",
    Semester: 7,
    SemesterColumnId: 7,
    ProgramSemester: 7,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 0,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 7",
    PrerequisiteSubjects: [
      {
        id: "403",
        name: "Software Engineering",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Software development methodologies",
      },
    ],
  },
  "subject-702-1704067200024-rst012uvw": {
    SubjectID: "702",
    SubjectName: "Professional Ethics in Computing",
    SubjectName_EN: "Professional Ethics in Computing",
    TotalCredits: 2,
    MajorID: "1",
    Semester: 7,
    SemesterColumnId: 7,
    ProgramSemester: 7,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 2,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 7",
    PrerequisiteSubjects: [],
  },

  // Core Subjects - Semester 8 (Final)
  "subject-801-1704067200025-uvw345xyz": {
    SubjectID: "801",
    SubjectName: "Capstone Project II",
    SubjectName_EN: "Capstone Project II",
    TotalCredits: 6,
    MajorID: "1",
    Semester: 8,
    SemesterColumnId: 8,
    ProgramSemester: 8,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 0,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Semester 8",
    PrerequisiteSubjects: [
      {
        id: "701",
        name: "Capstone Project I",
        credits: 6,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Initial capstone project work",
      },
    ],
  },
  "subject-802-1704067200026-xyz678abc": {
    SubjectID: "802",
    SubjectName: "Professional Internship",
    SubjectName_EN: "Professional Internship",
    TotalCredits: 4,
    MajorID: "1",
    Semester: 8,
    SemesterColumnId: 8,
    ProgramSemester: 8,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 0,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Semester 8",
    PrerequisiteSubjects: [],
  },

  // Physical Education Subjects
  "subject-pe101-1704067200027-def901ghi": {
    SubjectID: "PE101",
    SubjectName: "Physical Education I",
    SubjectName_EN: "Physical Education I",
    TotalCredits: 1,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 0,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "Physical Education 1",
    PrerequisiteSubjects: [],
  },
  "subject-pe201-1704067200028-ghi234jkl": {
    SubjectID: "PE201",
    SubjectName: "Physical Education II",
    SubjectName_EN: "Physical Education II",
    TotalCredits: 1,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 0,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "Physical Education 2",
    PrerequisiteSubjects: [
      {
        id: "PE101",
        name: "Physical Education I",
        credits: 1,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Basic physical fitness and sports",
      },
    ],
  },

  // English Course Subjects
  "subject-eng101-1704067200029-jkl567mno": {
    SubjectID: "ENG101",
    SubjectName: "English Communication I",
    SubjectName_EN: "English Communication I",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 1,
    SemesterColumnId: 1,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    SemesterName: "English Courses 1",
    PrerequisiteSubjects: [],
  },
  "subject-eng201-1704067200030-mno890pqr": {
    SubjectID: "ENG201",
    SubjectName: "English Communication II",
    SubjectName_EN: "English Communication II",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 2,
    SemesterColumnId: 2,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "English Courses 2",
    PrerequisiteSubjects: [
      {
        id: "ENG101",
        name: "English Communication I",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Basic English communication skills",
      },
    ],
  },
  "subject-eng301-1704067200031-pqr123stu": {
    SubjectID: "ENG301",
    SubjectName: "Technical English",
    SubjectName_EN: "Technical English",
    TotalCredits: 3,
    MajorID: "1",
    Semester: 3,
    SemesterColumnId: 3,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYear: 2024,
    AcademicYearID: 2024,
    LectureCredits: 3,
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    SemesterName: "English Courses 3",
    PrerequisiteSubjects: [
      {
        id: "ENG201",
        name: "English Communication II",
        credits: 3,
        faculty_id: 1,
        gradingFormulaId: 1,
        description: "Intermediate English communication",
      },
    ],
  },
};

// Complete curriculum state structure
export const FakeCompleteCurriculumState = {
  curriculumInfo: FakeCurriculumInfo,
  boards: FakeBoards,
  subjects: FakeCurriculumSubjects,
};

// Available subjects for search (these would be the subjects that can be added)
export const FakeAvailableSubjects = [
  {
    id: "105",
    name: "Chemistry I",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Basic chemistry concepts",
  },
  {
    id: "106",
    name: "Biology I",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Introduction to biology",
  },
  {
    id: "205",
    name: "Chemistry II",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Advanced chemistry",
  },
  {
    id: "305",
    name: "Quantum Computing",
    credits: 4,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Quantum algorithms and computing",
  },
  {
    id: "306",
    name: "Blockchain Technology",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Distributed ledger systems",
  },
  {
    id: "405",
    name: "Internet of Things",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "IoT systems and protocols",
  },
  {
    id: "505",
    name: "Advanced Algorithms",
    credits: 4,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Complex algorithmic techniques",
  },
  {
    id: "605",
    name: "Computer Graphics",
    credits: 3,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Graphics programming and visualization",
  },
  {
    id: "PHIL101",
    name: "Introduction to Philosophy",
    credits: 2,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Basic philosophical concepts",
  },
  {
    id: "PHIL201",
    name: "Ethics and Morality",
    credits: 2,
    faculty_id: 1,
    gradingFormulaId: 1,
    description: "Ethical reasoning and moral philosophy",
  },
];
