import {
  Calculator,
  DraftingCompass,
  LampWallDown,
  ScanEyeIcon,
  TextSearchIcon,
} from "lucide-react";
import { Class, Department, Student, Teacher, Subject } from "./model/model";
import { Formula } from "./model/FormulaModel";

export const teachers: Teacher[] = [
  {
    id: 1,
    name: "Dr. Emily Carter",
    location: "New York, USA",
    birthday: "1980-04-12",
    majorId: 1,
    departmentId: 1,
    isActivated: true,
    teacherEmail: "emily.carter@university.edu",
  },
  {
    id: 2,
    name: "Prof. James O'Neil",
    location: "Toronto, Canada",
    birthday: "1975-11-30",
    majorId: 4,
    departmentId: 5,
    isActivated: false,
    teacherEmail: "james.oneil@university.edu",
  },
  {
    id: 3,
    name: "Dr. Aisha Khan",
    location: "London, UK",
    birthday: "1987-07-21",
    majorId: 2,
    departmentId: 3,
    isActivated: true,
    teacherEmail: "aisha.khan@university.edu",
  },
  {
    id: 4,
    name: "Prof. Hiro Tanaka",
    location: "Tokyo, Japan",
    birthday: "1982-02-14",
    majorId: 1,
    departmentId: 7,
    isActivated: true,
    teacherEmail: "hiro.tanaka@university.edu",
  },
  {
    id: 5,
    name: "Dr. Laura Mendez",
    location: "Madrid, Spain",
    birthday: "1985-09-19",
    majorId: 4,
    departmentId: 2,
    isActivated: false,
    teacherEmail: "laura.mendez@university.edu",
  },
  {
    id: 6,
    name: "Dr. Samuel Lee",
    location: "Seoul, South Korea",
    birthday: "1978-06-15",
    majorId: 3,
    departmentId: 3,
    isActivated: true,
    teacherEmail: "samuel.lee@university.edu",
  },
  {
    id: 7,
    name: "Prof. Maria Rossi",
    location: "Rome, Italy",
    birthday: "1983-10-09",
    majorId: 2,
    departmentId: 2,
    isActivated: false,
    teacherEmail: "maria.rossi@university.edu",
  },
  {
    id: 8,
    name: "Dr. Ahmed Al-Farsi",
    location: "Dubai, UAE",
    birthday: "1981-03-25",
    majorId: 4,
    departmentId: 5,
    isActivated: true,
    teacherEmail: "ahmed.alfarsi@university.edu",
  },
  {
    id: 9,
    name: "Prof. Chloe Nguyen",
    location: "Ho Chi Minh City, Vietnam",
    birthday: "1986-12-02",
    majorId: 1,
    departmentId: 1,
    isActivated: true,
    teacherEmail: "chloe.nguyen@university.edu",
  },
  {
    id: 10,
    name: "Dr. Ivan Petrov",
    location: "Moscow, Russia",
    birthday: "1979-08-18",
    majorId: 3,
    departmentId: 7,
    isActivated: false,
    teacherEmail: "ivan.petrov@university.edu",
  },

  {
    id: 11,
    name: "Dr. Olivia Smith",
    location: "Sydney, Australia",
    birthday: "1984-05-10",
    majorId: 3,
    departmentId: 3,
    isActivated: true,
    teacherEmail: "olivia.smith@university.edu",
  },
  {
    id: 12,
    name: "Prof. Liam Brown",
    location: "Dublin, Ireland",
    birthday: "1977-09-23",
    majorId: 2,
    departmentId: 2,
    isActivated: false,
    teacherEmail: "liam.brown@university.edu",
  },
  {
    id: 13,
    name: "Dr. Sophia Martinez",
    location: "Buenos Aires, Argentina",
    birthday: "1982-11-15",
    majorId: 4,
    departmentId: 5,
    isActivated: true,
    teacherEmail: "sophia.martinez@university.edu",
  },
  {
    id: 14,
    name: "Prof. Noah Wilson",
    location: "Cape Town, South Africa",
    birthday: "1980-03-08",
    majorId: 1,
    departmentId: 1,
    isActivated: true,
    teacherEmail: "noah.wilson@university.edu",
  },
  {
    id: 15,
    name: "Dr. Isabella Garcia",
    location: "Santiago, Chile",
    birthday: "1986-07-19",
    majorId: 3,
    departmentId: 7,
    isActivated: false,
    teacherEmail: "isabella.garcia@university.edu",
  },
  {
    id: 16,
    name: "Prof. Ethan Davis",
    location: "Auckland, New Zealand",
    birthday: "1979-01-12",
    majorId: 2,
    departmentId: 3,
    isActivated: true,
    teacherEmail: "ethan.davis@university.edu",
  },
  {
    id: 17,
    name: "Dr. Mia Hernandez",
    location: "Lima, Peru",
    birthday: "1983-04-25",
    majorId: 4,
    departmentId: 2,
    isActivated: true,
    teacherEmail: "mia.hernandez@university.edu",
  },
  {
    id: 18,
    name: "Prof. Lucas White",
    location: "Edinburgh, Scotland",
    birthday: "1978-10-30",
    majorId: 1,
    departmentId: 7,
    isActivated: false,
    teacherEmail: "lucas.white@university.edu",
  },
  {
    id: 19,
    name: "Dr. Charlotte Lee",
    location: "Hong Kong, China",
    birthday: "1985-06-18",
    majorId: 3,
    departmentId: 3,
    isActivated: true,
    teacherEmail: "charlotte.lee@university.edu",
  },
  {
    id: 20,
    name: "Prof. Benjamin Kim",
    location: "Seoul, South Korea",
    birthday: "1981-02-05",
    majorId: 2,
    departmentId: 2,
    isActivated: true,
    teacherEmail: "benjamin.kim@university.edu",
  },
  {
    id: 21,
    name: "Dr. Amelia Clark",
    location: "Vancouver, Canada",
    birthday: "1987-09-14",
    majorId: 4,
    departmentId: 5,
    isActivated: false,
    teacherEmail: "amelia.clark@university.edu",
  },
  {
    id: 22,
    name: "Prof. Henry Walker",
    location: "Melbourne, Australia",
    birthday: "1980-12-03",
    majorId: 1,
    departmentId: 1,
    isActivated: true,
    teacherEmail: "henry.walker@university.edu",
  },
  {
    id: 23,
    name: "Dr. Grace Adams",
    location: "Oslo, Norway",
    birthday: "1984-08-27",
    majorId: 3,
    departmentId: 7,
    isActivated: true,
    teacherEmail: "grace.adams@university.edu",
  },
  {
    id: 24,
    name: "Prof. Jack Thompson",
    location: "Stockholm, Sweden",
    birthday: "1976-05-16",
    majorId: 2,
    departmentId: 3,
    isActivated: false,
    teacherEmail: "jack.thompson@university.edu",
  },
  {
    id: 25,
    name: "Dr. Ella Robinson",
    location: "Helsinki, Finland",
    birthday: "1983-03-22",
    majorId: 4,
    departmentId: 2,
    isActivated: true,
    teacherEmail: "ella.robinson@university.edu",
  },
  {
    id: 26,
    name: "Prof. Daniel Hall",
    location: "Vienna, Austria",
    birthday: "1979-07-09",
    majorId: 1,
    departmentId: 7,
    isActivated: true,
    teacherEmail: "daniel.hall@university.edu",
  },
  {
    id: 27,
    name: "Dr. Lily Young",
    location: "Zurich, Switzerland",
    birthday: "1986-11-02",
    majorId: 3,
    departmentId: 3,
    isActivated: false,
    teacherEmail: "lily.young@university.edu",
  },
  {
    id: 28,
    name: "Prof. Matthew King",
    location: "Amsterdam, Netherlands",
    birthday: "1982-06-29",
    majorId: 2,
    departmentId: 2,
    isActivated: true,
    teacherEmail: "matthew.king@university.edu",
  },
  {
    id: 29,
    name: "Dr. Chloe Scott",
    location: "Brussels, Belgium",
    birthday: "1981-01-08",
    majorId: 4,
    departmentId: 5,
    isActivated: true,
    teacherEmail: "chloe.scott@university.edu",
  },
  {
    id: 30,
    name: "Prof. James Evans",
    location: "Copenhagen, Denmark",
    birthday: "1978-04-14",
    majorId: 1,
    departmentId: 1,
    isActivated: false,
    teacherEmail: "james.evans@university.edu",
  },
];

export const classes: Class[] = [
  {
    id: 1,
    name: "BUS2024-A",
    majorId: 1,
    students: [], // Will populate below
  },
  {
    id: 2,
    name: "TECH2024-CS",
    majorId: 4,
    students: [],
  },
  {
    id: 3,
    name: "SCI2024-CH",
    majorId: 2,
    students: [],
  },
];

export const students: Student[] = [
  {
    id: 1,
    name: "Alice Johnson",
    username: "alice.j",
    classId: 1,
    location: "Chicago, USA",
    birthday: "2003-05-22",

    majorId: 1,
    departmentId: 1,
    isActivated: true,
    studentEmail: "alice.j@students.university.edu",
    studentId: "STU001",
  },
  {
    id: 2,
    name: "Mohamed El-Sayed",
    username: "mohamed.es",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Cairo, Egypt",
    birthday: "2002-12-11",
    isActivated: true,
    studentEmail: "mohamed.es@students.university.edu",
    studentId: "STU002",
  },
  {
    id: 3,
    name: "Lina Schneider",
    username: "lina.sch",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Berlin, Germany",
    birthday: "2004-01-17",
    isActivated: false,
    studentEmail: "lina.sch@students.university.edu",
    studentId: "STU003",
  },
  {
    id: 4,
    name: "Carlos Rodriguez",
    username: "carlos.rod",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Mexico City, Mexico",
    birthday: "2003-08-05",
    isActivated: true,
    studentEmail: "carlos.rod@students.university.edu",
    studentId: "STU004",
  },
  {
    id: 5,
    name: "Sophie Dubois",
    username: "sophie.db",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Paris, France",
    birthday: "2004-03-28",
    isActivated: true,
    studentEmail: "sophie.db@students.university.edu",
    studentId: "STU005",
  },
  {
    id: 6,
    name: "Emma Watson",
    username: "emma.w",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "London, UK",
    birthday: "2003-09-15",
    isActivated: true,
    studentEmail: "emma.w@students.university.edu",
    studentId: "STU006",
  },
  {
    id: 7,
    name: "Liam Smith",
    username: "liam.s",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "New York, USA",
    birthday: "2002-11-20",
    isActivated: true,
    studentEmail: "liam.s@students.university.edu",
    studentId: "STU007",
  },
  {
    id: 8,
    name: "Sophia Brown",
    username: "sophia.b",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Paris, France",
    birthday: "2004-02-10",
    isActivated: false,
    studentEmail: "sophia.b@students.university.edu",
    studentId: "STU008",
  },
  {
    id: 9,
    name: "Noah Davis",
    username: "noah.d",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Toronto, Canada",
    birthday: "2003-07-25",
    isActivated: true,
    studentEmail: "noah.d@students.university.edu",
    studentId: "STU009",
  },
  {
    id: 10,
    name: "Isabella Martinez",
    username: "isabella.m",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Madrid, Spain",
    birthday: "2002-05-30",
    isActivated: true,
    studentEmail: "isabella.m@students.university.edu",
    studentId: "STU010",
  },
  {
    id: 11,
    name: "Ethan Taylor",
    username: "ethan.t",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Los Angeles, USA",
    birthday: "2003-04-12",
    isActivated: true,
    studentEmail: "ethan.t@students.university.edu",
    studentId: "STU011",
  },
  {
    id: 12,
    name: "Olivia Wilson",
    username: "olivia.w",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Sydney, Australia",
    birthday: "2004-06-18",
    isActivated: true,
    studentEmail: "olivia.w@students.university.edu",
    studentId: "STU012",
  },
  {
    id: 13,
    name: "Liam Brown",
    username: "liam.b",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Dublin, Ireland",
    birthday: "2003-09-25",
    isActivated: true,
    studentEmail: "liam.b@students.university.edu",
    studentId: "STU013",
  },
  {
    id: 14,
    name: "Sophia Martinez",
    username: "sophia.m",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Buenos Aires, Argentina",
    birthday: "2002-11-15",
    isActivated: true,
    studentEmail: "sophia.m@students.university.edu",
    studentId: "STU014",
  },
  {
    id: 15,
    name: "Noah Garcia",
    username: "noah.g",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Madrid, Spain",
    birthday: "2003-07-19",
    isActivated: true,
    studentEmail: "noah.g@students.university.edu",
    studentId: "STU015",
  },
  {
    id: 16,
    name: "Emma Davis",
    username: "emma.d",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Paris, France",
    birthday: "2004-03-28",
    isActivated: true,
    studentEmail: "emma.d@students.university.edu",
    studentId: "STU016",
  },
  {
    id: 17,
    name: "James Lee",
    username: "james.l",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Seoul, South Korea",
    birthday: "2002-12-11",
    isActivated: true,
    studentEmail: "james.l@students.university.edu",
    studentId: "STU017",
  },
  {
    id: 18,
    name: "Isabella Kim",
    username: "isabella.k",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Toronto, Canada",
    birthday: "2003-09-15",
    isActivated: true,
    studentEmail: "isabella.k@students.university.edu",
    studentId: "STU018",
  },
  {
    id: 19,
    name: "Alexander White",
    username: "alexander.w",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "London, UK",
    birthday: "2004-01-17",
    isActivated: true,
    studentEmail: "alexander.w@students.university.edu",
    studentId: "STU019",
  },
  {
    id: 20,
    name: "Mia Johnson",
    username: "mia.j",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Chicago, USA",
    birthday: "2003-05-22",
    isActivated: true,
    studentEmail: "mia.j@students.university.edu",
    studentId: "STU020",
  },
  {
    id: 21,
    name: "Benjamin Brown",
    username: "benjamin.b",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Berlin, Germany",
    birthday: "2004-02-10",
    isActivated: true,
    studentEmail: "benjamin.b@students.university.edu",
    studentId: "STU021",
  },
  {
    id: 22,
    name: "Charlotte Taylor",
    username: "charlotte.t",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Mexico City, Mexico",
    birthday: "2003-08-05",
    isActivated: true,
    studentEmail: "charlotte.t@students.university.edu",
    studentId: "STU022",
  },
  {
    id: 23,
    name: "William Wilson",
    username: "william.w",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "New York, USA",
    birthday: "2002-11-20",
    isActivated: true,
    studentEmail: "william.w@students.university.edu",
    studentId: "STU023",
  },
  {
    id: 24,
    name: "Amelia Martinez",
    username: "amelia.m",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Rome, Italy",
    birthday: "2003-07-25",
    isActivated: true,
    studentEmail: "amelia.m@students.university.edu",
    studentId: "STU024",
  },
  {
    id: 25,
    name: "Lucas Garcia",
    username: "lucas.g",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Tokyo, Japan",
    birthday: "2004-03-28",
    isActivated: true,
    studentEmail: "lucas.g@students.university.edu",
    studentId: "STU025",
  },
  {
    id: 26,
    name: "Harper Davis",
    username: "harper.d",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Los Angeles, USA",
    birthday: "2003-04-12",
    isActivated: true,
    studentEmail: "harper.d@students.university.edu",
    studentId: "STU026",
  },
  {
    id: 27,
    name: "Ella Taylor",
    username: "ella.t",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Sydney, Australia",
    birthday: "2004-06-18",
    isActivated: true,
    studentEmail: "ella.t@students.university.edu",
    studentId: "STU027",
  },
  {
    id: 28,
    name: "Henry Brown",
    username: "henry.b",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Dublin, Ireland",
    birthday: "2003-09-25",
    isActivated: true,
    studentEmail: "henry.b@students.university.edu",
    studentId: "STU028",
  },
  {
    id: 29,
    name: "Ava Wilson",
    username: "ava.w",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Buenos Aires, Argentina",
    birthday: "2002-11-15",
    isActivated: true,
    studentEmail: "ava.w@students.university.edu",
    studentId: "STU029",
  },
  {
    id: 30,
    name: "Jack Martinez",
    username: "jack.m",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Madrid, Spain",
    birthday: "2003-07-19",
    isActivated: true,
    studentEmail: "jack.m@students.university.edu",
    studentId: "STU030",
  },
  {
    id: 31,
    name: "Emily Clark",
    username: "emily.c",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Boston, USA",
    birthday: "2003-02-14",
    isActivated: true,
    studentEmail: "emily.c@students.university.edu",
    studentId: "STU031",
  },
  {
    id: 32,
    name: "Daniel Johnson",
    username: "daniel.j",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "San Francisco, USA",
    birthday: "2004-04-20",
    isActivated: true,
    studentEmail: "daniel.j@students.university.edu",
    studentId: "STU032",
  },
  {
    id: 33,
    name: "Sophia Lee",
    username: "sophia.l",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Seoul, South Korea",
    birthday: "2003-11-11",
    isActivated: true,
    studentEmail: "sophia.l@students.university.edu",
    studentId: "STU033",
  },
  {
    id: 34,
    name: "James Brown",
    username: "james.b",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Chicago, USA",
    birthday: "2002-09-09",
    isActivated: true,
    studentEmail: "james.b@students.university.edu",
    studentId: "STU034",
  },
  {
    id: 35,
    name: "Olivia Martinez",
    username: "olivia.m",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Madrid, Spain",
    birthday: "2004-06-06",
    isActivated: true,
    studentEmail: "olivia.m@students.university.edu",
    studentId: "STU035",
  },
  {
    id: 36,
    name: "Liam Wilson",
    username: "liam.w",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "London, UK",
    birthday: "2003-03-03",
    isActivated: true,
    studentEmail: "liam.w@students.university.edu",
    studentId: "STU036",
  },
  {
    id: 37,
    name: "Emma Davis",
    username: "emma.d",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "New York, USA",
    birthday: "2002-12-12",
    isActivated: true,
    studentEmail: "emma.d@students.university.edu",
    studentId: "STU037",
  },
  {
    id: 38,
    name: "Noah Taylor",
    username: "noah.t",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Toronto, Canada",
    birthday: "2004-05-05",
    isActivated: true,
    studentEmail: "noah.t@students.university.edu",
    studentId: "STU038",
  },
  {
    id: 39,
    name: "Isabella White",
    username: "isabella.w",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Paris, France",
    birthday: "2003-07-07",
    isActivated: true,
    studentEmail: "isabella.w@students.university.edu",
    studentId: "STU039",
  },
  {
    id: 40,
    name: "William Harris",
    username: "william.h",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Los Angeles, USA",
    birthday: "2002-08-08",
    isActivated: true,
    studentEmail: "william.h@students.university.edu",
    studentId: "STU040",
  },
  {
    id: 41,
    name: "Mia Clark",
    username: "mia.c",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Sydney, Australia",
    birthday: "2004-01-01",
    isActivated: true,
    studentEmail: "mia.c@students.university.edu",
    studentId: "STU041",
  },
  {
    id: 42,
    name: "Alexander King",
    username: "alexander.k",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Berlin, Germany",
    birthday: "2003-10-10",
    isActivated: true,
    studentEmail: "alexander.k@students.university.edu",
    studentId: "STU042",
  },
  {
    id: 43,
    name: "Charlotte Adams",
    username: "charlotte.a",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Boston, USA",
    birthday: "2002-04-04",
    isActivated: true,
    studentEmail: "charlotte.a@students.university.edu",
    studentId: "STU043",
  },
  {
    id: 44,
    name: "Benjamin Scott",
    username: "benjamin.s",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "San Francisco, USA",
    birthday: "2004-09-09",
    isActivated: true,
    studentEmail: "benjamin.s@students.university.edu",
    studentId: "STU044",
  },
  {
    id: 45,
    name: "Amelia Brown",
    username: "amelia.b",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Seoul, South Korea",
    birthday: "2003-06-06",
    isActivated: true,
    studentEmail: "amelia.b@students.university.edu",
    studentId: "STU045",
  },
  {
    id: 46,
    name: "Lucas Martinez",
    username: "lucas.m",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Chicago, USA",
    birthday: "2002-03-03",
    isActivated: true,
    studentEmail: "lucas.m@students.university.edu",
    studentId: "STU046",
  },
  {
    id: 47,
    name: "Harper Wilson",
    username: "harper.w",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Madrid, Spain",
    birthday: "2004-07-07",
    isActivated: true,
    studentEmail: "harper.w@students.university.edu",
    studentId: "STU047",
  },
  {
    id: 48,
    name: "Ella Davis",
    username: "ella.d",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "London, UK",
    birthday: "2003-02-02",
    isActivated: true,
    studentEmail: "ella.d@students.university.edu",
    studentId: "STU048",
  },
  {
    id: 49,
    name: "Henry Taylor",
    username: "henry.t",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "New York, USA",
    birthday: "2002-01-01",
    isActivated: true,
    studentEmail: "henry.t@students.university.edu",
    studentId: "STU049",
  },
  {
    id: 50,
    name: "Ava White",
    username: "ava.w",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Toronto, Canada",
    birthday: "2004-08-08",
    isActivated: true,
    studentEmail: "ava.w@students.university.edu",
    studentId: "STU050",
  },
  {
    id: 51,
    name: "Jack Harris",
    username: "jack.h",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Paris, France",
    birthday: "2003-05-05",
    isActivated: true,
    studentEmail: "jack.h@students.university.edu",
    studentId: "STU051",
  },
  {
    id: 52,
    name: "Emily King",
    username: "emily.k",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Los Angeles, USA",
    birthday: "2002-11-11",
    isActivated: true,
    studentEmail: "emily.k@students.university.edu",
    studentId: "STU052",
  },
  {
    id: 53,
    name: "Daniel Adams",
    username: "daniel.a",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Sydney, Australia",
    birthday: "2004-03-03",
    isActivated: true,
    studentEmail: "daniel.a@students.university.edu",
    studentId: "STU053",
  },
  {
    id: 54,
    name: "Sophia Scott",
    username: "sophia.s",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Berlin, Germany",
    birthday: "2003-12-12",
    isActivated: true,
    studentEmail: "sophia.s@students.university.edu",
    studentId: "STU054",
  },
  {
    id: 55,
    name: "James Brown",
    username: "james.br",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Boston, USA",
    birthday: "2002-06-06",
    isActivated: true,
    studentEmail: "james.br@students.university.edu",
    studentId: "STU055",
  },
  {
    id: 56,
    name: "Olivia Martinez",
    username: "olivia.ma",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "San Francisco, USA",
    birthday: "2004-02-02",
    isActivated: true,
    studentEmail: "olivia.ma@students.university.edu",
    studentId: "STU056",
  },
  {
    id: 57,
    name: "Liam Wilson",
    username: "liam.wi",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "Seoul, South Korea",
    birthday: "2003-09-09",
    isActivated: true,
    studentEmail: "liam.wi@students.university.edu",
    studentId: "STU057",
  },
  {
    id: 58,
    name: "Emma Davis",
    username: "emma.da",
    classId: 1,
    majorId: 1,
    departmentId: 1,
    location: "Chicago, USA",
    birthday: "2002-07-07",
    isActivated: true,
    studentEmail: "emma.da@students.university.edu",
    studentId: "STU058",
  },
  {
    id: 59,
    name: "Noah Taylor",
    username: "noah.ta",
    classId: 2,
    majorId: 4,
    departmentId: 5,
    location: "Madrid, Spain",
    birthday: "2004-10-10",
    isActivated: true,
    studentEmail: "noah.ta@students.university.edu",
    studentId: "STU059",
  },
  {
    id: 60,
    name: "Isabella White",
    username: "isabella.wh",
    classId: 3,
    majorId: 2,
    departmentId: 3,
    location: "London, UK",
    birthday: "2003-01-01",
    isActivated: true,
    studentEmail: "isabella.wh@students.university.edu",
    studentId: "STU060",
  },
];

classes.forEach((cls) => {
  cls.students = students.filter((s) => s.classId === cls.id);
});

export const genders = [
  { id: 1, name: "Male" },
  { id: 2, name: "Female" },
];

export const majorData: Record<number, { id: number; name: string }[]> = {
  1: [
    { id: 1, name: "Accounting" },
    { id: 2, name: "Marketing" },
    { id: 3, name: "Finance" },
    { id: 4, name: "Management" },
  ],
  2: [
    { id: 1, name: "Music" },
    { id: 2, name: "Visual Arts" },
    { id: 3, name: "Performing Arts" },
    { id: 4, name: "Literature" },
  ],
  3: [
    { id: 1, name: "Biology" },
    { id: 2, name: "Chemistry" },
    { id: 3, name: "Physics" },
    { id: 4, name: "Mathematics" },
  ],
  4: [
    { id: 1, name: "Criminal Law" },
    { id: 2, name: "Corporate Law" },
    { id: 3, name: "International Law" },
    { id: 4, name: "Constitutional Law" },
  ],
  5: [
    { id: 1, name: "Information Systems" },
    { id: 2, name: "AI" },
    { id: 3, name: "Cybersecurity" },
    { id: 4, name: "Computer Science" },
  ],
};

export const departmentData: Department[] = [
  {
    id: 1,
    name: "Business",
    description: "Department of Business and Management studies.",
    majors: [
      {
        id: 1,
        name: "Accounting",
        departmentId: 1,
        description: "Study of financial reporting, auditing, and budgeting.",
      },
      {
        id: 2,
        name: "Marketing",
        departmentId: 1,
        description:
          "Exploration of consumer behavior, branding, and advertising.",
      },
      {
        id: 3,
        name: "Finance",
        departmentId: 1,
        description: "Focus on investments, banking, and financial planning.",
      },
      {
        id: 4,
        name: "Management",
        departmentId: 1,
        description: "Learning how to lead, organize, and operate businesses.",
      },
    ],
    icon: "Calculator",
  },
  {
    id: 2,
    name: "Arts",
    description: "Department of Fine Arts and Humanities.",
    majors: [
      {
        id: 1,
        name: "Music",
        departmentId: 2,
        description: "Performance, theory, and composition of music.",
      },
      {
        id: 2,
        name: "Visual Arts",
        departmentId: 2,
        description: "Study of painting, sculpture, and other visual mediums.",
      },
      {
        id: 3,
        name: "Performing Arts",
        departmentId: 2,
        description: "Focus on theater, dance, and live performance.",
      },
      {
        id: 4,
        name: "Literature",
        departmentId: 2,
        description:
          "Analysis of written works from various cultures and periods.",
      },
    ],
    icon: "DraftingCompass",
  },
  {
    id: 3,
    name: "Science",
    description: "Department of Natural Sciences.",
    majors: [
      {
        id: 1,
        name: "Biology",
        departmentId: 3,
        description: "Study of living organisms and ecosystems.",
      },
      {
        id: 2,
        name: "Chemistry",
        departmentId: 3,
        description: "Understanding matter, its properties, and reactions.",
      },
      {
        id: 3,
        name: "Physics",
        departmentId: 3,
        description:
          "Exploring the fundamental laws of nature and the universe.",
      },
      {
        id: 4,
        name: "Mathematics",
        departmentId: 3,
        description: "The abstract science of number, quantity, and space.",
      },
    ],
    icon: "ScanEyeIcon",
  },
  {
    id: 4,
    name: "Law",
    description: "Department of Legal Studies.",
    majors: [
      {
        id: 1,
        name: "Criminal Law",
        departmentId: 4,
        description: "Legal systems dealing with crime and punishment.",
      },
      {
        id: 2,
        name: "Corporate Law",
        departmentId: 4,
        description: "Laws governing businesses and corporate practices.",
      },
      {
        id: 3,
        name: "International Law",
        departmentId: 4,
        description: "Legal frameworks between nations and global entities.",
      },
      {
        id: 4,
        name: "Constitutional Law",
        departmentId: 4,
        description:
          "Interpretation and application of constitutional principles.",
      },
    ],
    icon: "LampWallDown",
  },
  {
    id: 5,
    name: "Technology",
    description: "Department of Technology and Innovation.",
    majors: [
      {
        id: 1,
        name: "Information Systems",
        departmentId: 5,
        description: "Integration of IT solutions with business processes.",
      },
      {
        id: 2,
        name: "AI",
        departmentId: 5,
        description:
          "Design and development of intelligent systems and algorithms.",
      },
      {
        id: 3,
        name: "Cybersecurity",
        departmentId: 5,
        description:
          "Protection of digital systems and data from cyber threats.",
      },
      {
        id: 4,
        name: "Computer Science",
        departmentId: 5,
        description:
          "Core principles of computing, software, and data structures.",
      },
    ],
    icon: "TextSearchIcon",
  },
  {
    id: 6,
    name: "Medicine",
    description: "Department of Medical and Health Sciences.",
    majors: [
      {
        id: 1,
        name: "General Medicine",
        departmentId: 6,
        description: "Comprehensive study of human health and diseases.",
      },
      {
        id: 2,
        name: "Nursing",
        departmentId: 6,
        description:
          "Healthcare practices focusing on patient care and support.",
      },
      {
        id: 3,
        name: "Pharmacy",
        departmentId: 6,
        description:
          "Study of drugs, their uses, and effects on the human body.",
      },
      {
        id: 4,
        name: "Public Health",
        departmentId: 6,
        description:
          "Promotion of community health through prevention and education.",
      },
    ],
    icon: "Calculator",
  },
  {
    id: 7,
    name: "Engineering",
    description: "Department of Engineering and Applied Sciences.",
    majors: [
      {
        id: 1,
        name: "Mechanical Engineering",
        departmentId: 7,
        description: "Design and manufacturing of mechanical systems.",
      },
      {
        id: 2,
        name: "Electrical Engineering",
        departmentId: 7,
        description: "Study of electrical circuits, systems, and devices.",
      },
      {
        id: 3,
        name: "Civil Engineering",
        departmentId: 7,
        description:
          "Construction and maintenance of infrastructure and buildings.",
      },
      {
        id: 4,
        name: "Software Engineering",
        departmentId: 7,
        description: "Development of scalable and reliable software systems.",
      },
    ],
    icon: "DraftingCompass",
  },
  {
    id: 8,
    name: "Education",
    description: "Department of Education and Teacher Training.",
    majors: [
      {
        id: 1,
        name: "Early Childhood Education",
        departmentId: 8,
        description: "Teaching methods and development for young learners.",
      },
      {
        id: 2,
        name: "Special Education",
        departmentId: 8,
        description: "Education strategies for students with diverse needs.",
      },
      {
        id: 3,
        name: "Curriculum Development",
        departmentId: 8,
        description: "Design and evaluation of educational programs.",
      },
      {
        id: 4,
        name: "Educational Psychology",
        departmentId: 8,
        description: "Psychological principles applied to education.",
      },
    ],
    icon: "LampWallDown",
  },
  {
    id: 9,
    name: "Social Sciences",
    description: "Department of Social and Behavioral Sciences.",
    majors: [
      {
        id: 1,
        name: "Psychology",
        departmentId: 9,
        description: "Study of the mind, behavior, and mental processes.",
      },
      {
        id: 2,
        name: "Sociology",
        departmentId: 9,
        description:
          "Examination of society, social structures, and relationships.",
      },
      {
        id: 3,
        name: "Political Science",
        departmentId: 9,
        description: "Analysis of political systems, theory, and governance.",
      },
      {
        id: 4,
        name: "Anthropology",
        departmentId: 9,
        description: "Study of human cultures, evolution, and societies.",
      },
    ],
    icon: "ScanEyeIcon",
  },
  {
    id: 10,
    name: "Environmental Studies",
    description: "Department of Environmental and Earth Sciences.",
    majors: [
      {
        id: 1,
        name: "Environmental Science",
        departmentId: 10,
        description:
          "Investigation of environmental systems and sustainability.",
      },
      {
        id: 2,
        name: "Geology",
        departmentId: 10,
        description: "Study of Earth's physical structure and history.",
      },
      {
        id: 3,
        name: "Climate Studies",
        departmentId: 10,
        description: "Research on climate systems and global change.",
      },
      {
        id: 4,
        name: "Sustainability",
        departmentId: 10,
        description: "Strategies for balancing human and ecological systems.",
      },
    ],
    icon: "TextSearchIcon",
  },

  {
    id: 11,
    name: "Architecture",
    description: "Department of Architecture and Urban Planning.",
    majors: [
      {
        id: 1,
        name: "Urban Design",
        departmentId: 11,
        description: "Planning and designing urban spaces and environments.",
      },
      {
        id: 2,
        name: "Landscape Architecture",
        departmentId: 11,
        description: "Design of outdoor spaces, landmarks, and structures.",
      },
      {
        id: 3,
        name: "Interior Architecture",
        departmentId: 11,
        description: "Focus on designing interior spaces and environments.",
      },
      {
        id: 4,
        name: "Sustainable Architecture",
        departmentId: 11,
        description: "Designing buildings with environmental sustainability.",
      },
    ],
    icon: "DraftingCompass",
  },
  {
    id: 12,
    name: "Media Studies",
    description: "Department of Media and Communication.",
    majors: [
      {
        id: 1,
        name: "Journalism",
        departmentId: 12,
        description: "Study of news reporting and media ethics.",
      },
      {
        id: 2,
        name: "Film Studies",
        departmentId: 12,
        description: "Analysis and production of films and visual media.",
      },
      {
        id: 3,
        name: "Public Relations",
        departmentId: 12,
        description: "Managing communication between organizations and public.",
      },
      {
        id: 4,
        name: "Digital Media",
        departmentId: 12,
        description: "Exploration of online platforms and digital content.",
      },
    ],
    icon: "LampWallDown",
  },
];

export const subjects: Subject[] = [
  {
    id: "1",
    subjectId: "101",
    name: "Financial Accounting",
    description: "Introduction to financial reporting and analysis.",
    majorId: "1",
    departmentId: 1,
    credits: 3,
  },
  {
    id: "2", 
    subjectId: "102",
    name: "Marketing Strategies",
    description: "Study of consumer behavior and branding techniques.",
    majorId: "2",
    departmentId: 1,
    credits: 3,
  },
  {
    id: "3",
    subjectId: "103",
    name: "Corporate Finance",
    description: "Focus on investment and financial management.",
    majorId: "3",
    departmentId: 1,
    credits: 4,
  },
  {
    id: "4",
    subjectId: "104",
    name: "Organizational Leadership",
    description: "Principles of management and leadership in organizations.",
    majorId: "4",
    departmentId: 1,
    credits: 3,
  },
  {
    id: "5",
    subjectId: "201",
    name: "Music Theory",
    description: "Study of musical structures and composition.",
    majorId: "1",
    departmentId: 2,
    credits: 3,
  },
  {
    id: "6",
    subjectId: "202",
    name: "Art History",
    description: "Exploration of visual arts across cultures and time.",
    majorId: "2",
    departmentId: 2,
    credits: 3,
  },
  {
    id: "7",
    subjectId: "203",
    name: "Theater Performance",
    description: "Practical and theoretical aspects of performing arts.",
    majorId: "3",
    departmentId: 2,
    credits: 4,
  },
  {
    id: "8",
    subjectId: "204",
    name: "World Literature",
    description: "Analysis of literary works from various cultures.",
    majorId: "4",
    departmentId: 2,
    credits: 3,
  },
  {
    id: "9",
    subjectId: "301",
    name: "Cell Biology",
    description: "Study of cellular structures and functions.",
    majorId: "1",
    departmentId: 3,
    credits: 4,
  },
  {
    id: "10",
    subjectId: "302",
    name: "Organic Chemistry",
    description:
      "Understanding the structure and reactions of organic compounds.",
    majorId: "2",
    departmentId: 3,
    credits: 4,
  },
  {
    id: "11",
    subjectId: "303",
    name: "Classical Mechanics",
    description: "Exploration of motion and forces in physical systems.",
    majorId: "3",
    departmentId: 3,
    credits: 4,
  },
  {
    id: "12",
    subjectId: "304",
    name: "Linear Algebra",
    description: "Study of vector spaces and linear transformations.",
    majorId: "4",
    departmentId: 3,
    credits: 3,
  },
  {
    id: "13",
    subjectId: "401",
    name: "Criminal Justice",
    description: "Overview of criminal law and justice systems.",
    majorId: "1",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "14",
    subjectId: "402",
    name: "Corporate Governance",
    description: "Study of laws governing corporate practices.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "15",
    subjectId: "403",
    name: "International Treaties",
    description: "Legal frameworks for international agreements.",
    majorId: "3",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "16",
    subjectId: "404",
    name: "Constitutional Law",
    description:
      "Analysis of constitutional principles and their applications.",
    majorId: "4",
    departmentId: 4,
    credits: 4,
  },
  {
    id: "17",
    subjectId: "501",
    name: "Database Systems",
    description: "Design and management of database systems.",
    majorId: "1",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "18",
    subjectId: "502",
    name: "Machine Learning",
    description: "Introduction to algorithms and models in AI.",
    majorId: "2",
    departmentId: 5,
    credits: 4,
  },
  {
    id: "19",
    subjectId: "503",
    name: "Network Security",
    description: "Techniques for securing digital networks.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "20",
    subjectId: "504",
    name: "Data Structures",
    description: "Core principles of data organization and manipulation.",
    majorId: "4",
    departmentId: 5,
    credits: 3,
  },
];

export const PESubjects  :Subject[] = [
  {
    id: "101",
    subjectId: "1001",
    name: "Basketball Fundamentals",
    description: "Basic skills and rules of basketball.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "102", 
    subjectId: "1002",
    name: "Swimming",
    description: "Swimming techniques and water safety.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "103",
    subjectId: "1003", 
    name: "Volleyball",
    description: "Fundamentals of volleyball gameplay.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "104",
    subjectId: "1004",
    name: "Track and Field",
    description: "Running, jumping and throwing techniques.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "105",
    subjectId: "1005",
    name: "Fitness Training",
    description: "Strength and conditioning exercises.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "106",
    subjectId: "1006",
    name: "Badminton",
    description: "Singles and doubles badminton skills.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "107",
    subjectId: "1007",
    name: "Table Tennis",
    description: "Basic and advanced table tennis techniques.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "108",
    subjectId: "1008",
    name: "Soccer",
    description: "Soccer skills and team strategies.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "109",
    subjectId: "1009",
    name: "Tennis",
    description: "Tennis fundamentals and court play.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "110",
    subjectId: "1010",
    name: "Aerobics",
    description: "Cardio exercises and rhythmic movements.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "111",
    subjectId: "1011",
    name: "Martial Arts",
    description: "Basic self-defense and martial arts principles.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "112",
    subjectId: "1012",
    name: "Dance Sports",
    description: "Various dance styles and choreography.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "113",
    subjectId: "1013",
    name: "Golf",
    description: "Golf swing mechanics and course etiquette.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "114",
    subjectId: "1014",
    name: "Rock Climbing",
    description: "Indoor climbing techniques and safety.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "115",
    subjectId: "1015",
    name: "Yoga",
    description: "Basic yoga poses and breathing techniques.",
    majorId: "1",
    departmentId: 6,
    credits: 2,
  }
];

export const philosophySubjects: Subject[] = [
  {
    id: "201",
    subjectId: "2001",
    name: "Introduction to Philosophy",
    description: "Fundamental concepts and major philosophical traditions.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "202", 
    subjectId: "2002",
    name: "Ethics and Moral Philosophy",
    description: "Ethical theories, moral reasoning and contemporary issues.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "203",
    subjectId: "2003",
    name: "Logic and Critical Thinking",
    description: "Principles of valid reasoning and argumentation.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "204",
    subjectId: "2004",
    name: "Ancient Philosophy",
    description: "Pre-Socratic, Platonic and Aristotelian philosophy.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "205",
    subjectId: "2005",
    name: "Modern Philosophy",
    description: "Major philosophical developments from 17th to 19th century.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "206",
    subjectId: "2006",
    name: "Existentialism",
    description: "Study of existence, freedom and meaning in human life.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "207",
    subjectId: "2007",
    name: "Philosophy of Mind",
    description: "Nature of consciousness, mind-body problem and cognition.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "208",
    subjectId: "2008",
    name: "Political Philosophy",
    description: "Theories of justice, power, and social organization.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "209",
    subjectId: "2009",
    name: "Eastern Philosophy",
    description: "Buddhist, Hindu, and Chinese philosophical traditions.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  },
  {
    id: "210",
    subjectId: "2010",
    name: "Philosophy of Science",
    description: "Scientific method, causation and theory development.",
    majorId: "2",
    departmentId: 4,
    credits: 3,
  }
];

export const englishSubjects: Subject[] = [
  {
    id: "301",
    subjectId: "3001",
    name: "Basic English",
    description: "Fundamental English grammar, vocabulary and communication skills.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "302", 
    subjectId: "3002",
    name: "Intermediate English",
    description: "Advanced grammar structures, academic writing and reading comprehension.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "303",
    subjectId: "3003", 
    name: "Upper Intermediate English",
    description: "Complex language structures, academic essays and critical analysis.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "304",
    subjectId: "3004",
    name: "Advanced English",
    description: "Professional writing, advanced reading and speaking skills.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  },
  {
    id: "305",
    subjectId: "3005",
    name: "Proficiency English",
    description: "Native-level fluency, academic research and professional communication.",
    majorId: "3",
    departmentId: 5,
    credits: 3,
  }
];

export const skillSubjects: Subject[] = [
  {
    id: "401",
    subjectId: "4001",
    name: "Critical Thinking",
    description: "Develop analytical and logical reasoning skills for problem-solving.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "402",
    subjectId: "4002", 
    name: "Public Speaking",
    description: "Master presentation skills and confident communication techniques.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "403",
    subjectId: "4003",
    name: "Digital Literacy",
    description: "Essential computer skills and digital tools proficiency.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "404",
    subjectId: "4004",
    name: "Project Management",
    description: "Planning, execution and monitoring of projects using modern methodologies.",
    majorId: "4",
    departmentId: 6,
    credits: 3,
  },
  {
    id: "405",
    subjectId: "4005",
    name: "Leadership Skills",
    description: "Team management, decision making and organizational leadership.",
    majorId: "4",
    departmentId: 6,
    credits: 3,
  },
  {
    id: "406",
    subjectId: "4006",
    name: "Time Management",
    description: "Productivity techniques and efficient scheduling strategies.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "407",
    subjectId: "4007",
    name: "Research Methods",
    description: "Academic research skills and methodology fundamentals.",
    majorId: "4",
    departmentId: 6,
    credits: 3,
  },
  {
    id: "408",
    subjectId: "4008",
    name: "Creative Problem Solving",
    description: "Innovation techniques and design thinking approaches.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  },
  {
    id: "409",
    subjectId: "4009",
    name: "Professional Writing",
    description: "Business communication and technical documentation skills.",
    majorId: "4",
    departmentId: 6,
    credits: 3,
  },
  {
    id: "410",
    subjectId: "4010",
    name: "Interpersonal Skills",
    description: "Effective communication and relationship building in professional settings.",
    majorId: "4",
    departmentId: 6,
    credits: 2,
  }
];


export const formulaSubjects: Formula[] = [
  {
    id: 1,
    name: "Standard Weighted Average",
    description: "Basic weighted formula combining participation, tests, and final exam",
    formula: "(participation * 0.1) + (midtermTest * 0.2) + (midtermReport * 0.3) + (final * 0.4)",
    participation: 10,
    midtermTest: 20,
    midtermReport: 30,
    final: 40
  },
  {
    id: 2,
    name: "Heavy Final Emphasis",
    description: "Formula that heavily weights the final examination",
    formula: "(participation * 0.05) + (midtermTest * 0.15) + (midtermReport * 0.2) + (final * 0.6)",
    participation: 5,
    midtermTest: 15,
    midtermReport: 20,
    final: 60
  },
  {
    id: 3,
    name: "Continuous Assessment",
    description: "Balanced approach emphasizing ongoing evaluation",
    formula: "(participation * 0.25) + (midtermTest * 0.25) + (midtermReport * 0.25) + (final * 0.25)",
    participation: 25,
    midtermTest: 25,
    midtermReport: 25,
    final: 25
  },
  {
    id: 4,
    name: "Participation Focused",
    description: "Formula that values active participation and engagement",
    formula: "(participation * 0.3) + (midtermTest * 0.2) + (midtermReport * 0.2) + (final * 0.3)",
    participation: 30,
    midtermTest: 20,
    midtermReport: 20,
    final: 30
  },
  {
    id: 5,
    name: "Research Intensive",
    description: "Emphasizes midterm reports and research projects",
    formula: "(participation * 0.1) + (midtermTest * 0.15) + (midtermReport * 0.5) + (final * 0.25)",
    participation: 10,
    midtermTest: 15,
    midtermReport: 50,
    final: 25
  }
]


export const curriculumData = [
  {
    id: 1,
    name: "Sơ đồ đào tạo - Khoa học máy tính",
    academicYear: "2025",
    department: "Khoa Công nghệ thông tin",
    major: "Khoa học máy tính",
    totalCredits: 120,
    totalCourses: 40,
    status: "active"
  },
  {
    id: 2,
    name: "Sơ đồ đào tạo - Mạng máy tính",
    academicYear: "2025",
    department: "Khoa Công nghệ thông tin",
    major: "Mạng máy tính",
    totalCredits: 125,
    totalCourses: 42,
    status: "active"
  },
  {
    id: 3,
    name: "Sơ đồ đào tạo - An toàn thông tin",
    academicYear: "2024",
    department: "Khoa Công nghệ thông tin",
    major: "An toàn thông tin",
    totalCredits: 130,
    totalCourses: 45,
    status: "inactive"
  },
  {
    id: 4,
    name: "Sơ đồ đào tạo - Kỹ thuật phần mềm",
    academicYear: "2025",
    department: "Khoa Công nghệ thông tin",
    major: "Kỹ thuật phần mềm",
    totalCredits: 128,
    totalCourses: 43,
    status: "draft"
  },
  {
    id: 5,
    name: "Sơ đồ đào tạo - Trí tuệ nhân tạo",
    academicYear: "2025",
    department: "Khoa Công nghệ thông tin",
    major: "Trí tuệ nhân tạo",
    totalCredits: 135,
    totalCourses: 46,
    status: "active"
  },
  {
    id: 6,
    name: "Sơ đồ đào tạo - Kinh tế",
    academicYear: "2025",
    department: "Khoa Kinh tế",
    major: "Kinh tế học",
    totalCredits: 110,
    totalCourses: 38,
    status: "active"
  },
  {
    id: 7,
    name: "Sơ đồ đào tạo - Quản trị kinh doanh",
    academicYear: "2024",
    department: "Khoa Kinh tế",
    major: "Quản trị kinh doanh",
    totalCredits: 115,
    totalCourses: 40,
    status: "inactive"
  },
  {
    id: 8,
    name: "Sơ đồ đào tạo - Tài chính ngân hàng",
    academicYear: "2025",
    department: "Khoa Kinh tế",
    major: "Tài chính ngân hàng",
    totalCredits: 118,
    totalCourses: 41,
    status: "draft"
  }
]
