export const FakeCurriclumnData = [
  // Semester 1 - 18 credits
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501001",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Calculus I",
    SubjectName_EN: "Calculus I",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Basic calculus concepts and applications</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501002",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Physics I",
    SubjectName_EN: "Physics I",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Basic physics principles and mechanics</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 2,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501003",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Introduction to Programming",
    SubjectName_EN: "Introduction to Programming",
    TotalCredits: 4,
    LectureCredits: 2,
    PracticeCredits: 2,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Basic programming concepts and algorithms</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 30,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 120,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501004",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "English 1",
    SubjectName_EN: "English 1",
    TotalCredits: 2,
    LectureCredits: 2,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Basic English communication skills</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501005",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Marxist-Leninist Philosophy",
    SubjectName_EN: "Marxist-Leninist Philosophy",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Philosophy and political theory</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "501006",
    Semester: 1,
    AcademicYear: 2021,
    ProgramSemester: 1,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Computer Literacy",
    SubjectName_EN: "Computer Literacy",
    TotalCredits: 3,
    LectureCredits: 2,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 1/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Basic computer skills and software applications</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },

  // Semester 2 - 18 credits
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503005",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Object-Oriented Programming",
    SubjectName_EN: "Object-Oriented Programming",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-503005' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Introduction to Programming (501003)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info:
      "<p>Topics include: object-oriented concepts and modeling, classes and methods, constructing and solving object-oriented problems, encapsulation, inheritance, abstraction, polymorphism, built-in storage objects in Java, inner classes, design patterns. Implementation in Java programming language.</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 30,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 120,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "501003",
        SubjectName: "Introduction to Programming",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "502001",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Calculus II",
    SubjectName_EN: "Calculus II",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-502001' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Calculus I (501001)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Advanced calculus concepts and applications</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "501001",
        SubjectName: "Calculus I",
      },
    ],
  },
  {
    LectureHours: 2,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "502002",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Data Structures and Algorithms",
    SubjectName_EN: "Data Structures and Algorithms",
    TotalCredits: 3,
    LectureCredits: 2,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-502002' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Introduction to Programming (501003)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Fundamental data structures and algorithms</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "501003",
        SubjectName: "Introduction to Programming",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "502003",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Linear Algebra",
    SubjectName_EN: "Linear Algebra",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Linear algebra concepts and applications</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "502004",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "English 2",
    SubjectName_EN: "English 2",
    TotalCredits: 2,
    LectureCredits: 2,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-502004' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - English 1 (501004)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Intermediate English communication skills</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "501004",
        SubjectName: "English 1",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "502005",
    Semester: 2,
    AcademicYear: 2021,
    ProgramSemester: 2,
    IsRequired: true,
    AcademicYearID: 2021,
    SubjectName: "Political Economy",
    SubjectName_EN: "Political Economy",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 2/2021-2022",
    IsSummerSemester: false,
    AUN_Info: "<p>Economic theory and political concepts</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },

  // Semester 3 - 18 credits
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503001",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Computer Networks",
    SubjectName_EN: "Computer Networks",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Network protocols, architectures, and security</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 30,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 120,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503002",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Database Systems",
    SubjectName_EN: "Database Systems",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-503002' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Data Structures and Algorithms (502002)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Database design, SQL, and database management</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "502002",
        SubjectName: "Data Structures and Algorithms",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503003",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Statistics and Probability",
    SubjectName_EN: "Statistics and Probability",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-503003' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Calculus II (502001)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Statistical analysis and probability theory</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "502001",
        SubjectName: "Calculus II",
      },
    ],
  },
  {
    LectureHours: 2,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503004",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Computer Architecture",
    SubjectName_EN: "Computer Architecture",
    TotalCredits: 3,
    LectureCredits: 2,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Major Knowledge",
    CourseTypeName_EN: "B.1     Major Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Computer organization and architecture principles</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503006",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "English 3",
    SubjectName_EN: "English 3",
    TotalCredits: 2,
    LectureCredits: 2,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-503006' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - English 2 (502004)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Advanced English communication skills</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "502004",
        SubjectName: "English 2",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503007",
    Semester: 3,
    AcademicYear: 2022,
    ProgramSemester: 3,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Scientific Socialism",
    SubjectName_EN: "Scientific Socialism",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 3/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Socialist theory and practice</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },

  // Semester 4 - 17 credits
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504001",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Data Structures and Algorithms",
    SubjectName_EN: "Data Structures and Algorithms",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-504001' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Programming Fundamentals (502003)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "CORE",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Core Subjects",
    CourseTypeName_EN: "B.1     Core Subjects",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Data structures, algorithms, and complexity analysis</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "502003",
        SubjectName: "Programming Fundamentals",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504002",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Computer Networks",
    SubjectName_EN: "Computer Networks",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "CORE",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Core Subjects",
    CourseTypeName_EN: "B.1     Core Subjects",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Network protocols, architecture, and security</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504003",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Database Systems",
    SubjectName_EN: "Database Systems",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "CORE",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Core Subjects",
    CourseTypeName_EN: "B.1     Core Subjects",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Database design, SQL, and database management systems</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504004",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Software Engineering",
    SubjectName_EN: "Software Engineering",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "CORE",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "B.1     Core Subjects",
    CourseTypeName_EN: "B.1     Core Subjects",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Software development methodologies and project management</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503008",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Ho Chi Minh Thought",
    SubjectName_EN: "Ho Chi Minh Thought",
    TotalCredits: 2,
    LectureCredits: 2,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Study of Ho Chi Minh's philosophy and ideology</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 1,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "503009",
    Semester: 4,
    AcademicYear: 2022,
    ProgramSemester: 4,
    IsRequired: true,
    AcademicYearID: 2022,
    SubjectName: "Physical Education 4",
    SubjectName_EN: "Physical Education 4",
    TotalCredits: 1,
    LectureCredits: 0,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17576,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.1     General Knowledge",
    CourseTypeName_EN: "A.1     General Knowledge",
    SemesterName: "Semester 4/2022-2023",
    IsSummerSemester: false,
    AUN_Info: "<p>Advanced sports and fitness activities</p>",
    CourseGroupID: "17576",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 0,
    SelfStudyHoursCount: 15,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  // Semester 5 - Computer Networks Major Core Subjects
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504001",
    Semester: 5,
    AcademicYear: 2023,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Computer Networks Fundamentals",
    SubjectName_EN: "Computer Networks Fundamentals",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-504001' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Data Structures and Algorithms (503005)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 5/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Introduction to computer networking principles, protocols, and architecture</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "503005",
        SubjectName: "Data Structures and Algorithms",
      },
    ],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504002",
    Semester: 5,
    AcademicYear: 2023,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Operating Systems",
    SubjectName_EN: "Operating Systems",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 5/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Study of operating system concepts, processes, memory management, and file systems</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 2,
    PracticeHours: 2,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504003",
    Semester: 5,
    AcademicYear: 2023,
    ProgramSemester: 5,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Network Programming",
    SubjectName_EN: "Network Programming",
    TotalCredits: 4,
    LectureCredits: 2,
    PracticeCredits: 2,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 5/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Programming applications for networked environments using sockets and protocols</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 30,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  // Semester 6
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504004",
    Semester: 6,
    AcademicYear: 2023,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Network Security",
    SubjectName_EN: "Network Security",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-504004' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Computer Networks Fundamentals (504001)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 6/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Network security principles, cryptography, firewalls, and intrusion detection</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "504001",
        SubjectName: "Computer Networks Fundamentals",
      },
    ],
  },
  {
    LectureHours: 2,
    PracticeHours: 2,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504005",
    Semester: 6,
    AcademicYear: 2023,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Database Systems",
    SubjectName_EN: "Database Systems",
    TotalCredits: 4,
    LectureCredits: 2,
    PracticeCredits: 2,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 6/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Database design, SQL, transaction processing, and database administration</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 30,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504006",
    Semester: 6,
    AcademicYear: 2023,
    ProgramSemester: 6,
    IsRequired: true,
    AcademicYearID: 2023,
    SubjectName: "Wireless Networks",
    SubjectName_EN: "Wireless Networks",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17578,
    TrainingMajorCode: "ELECTIVE",
    CourseTypeColorBackground: "#FFF3E0",
    CourseTypeColorFont: "#F57C00",
    CourseTypeName: "B.2     Major Elective Subjects",
    CourseTypeName_EN: "B.2     Major Elective Subjects",
    SemesterName: "Semester 6/2023-2024",
    IsSummerSemester: false,
    AUN_Info: "<p>Wireless communication technologies, mobile networks, and IoT</p>",
    CourseGroupID: "17578",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 3,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 1,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  // Semester 7
  {
    LectureHours: 3,
    PracticeHours: 1,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504007",
    Semester: 7,
    AcademicYear: 2024,
    ProgramSemester: 7,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Network Management",
    SubjectName_EN: "Network Management",
    TotalCredits: 4,
    LectureCredits: 3,
    PracticeCredits: 1,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-504007' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Network Security (504004)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17577,
    TrainingMajorCode: "MAJOR",
    CourseTypeColorBackground: "#E3F2FD",
    CourseTypeColorFont: "#1976D2",
    CourseTypeName: "B.1     Major Core Subjects",
    CourseTypeName_EN: "B.1     Major Core Subjects",
    SemesterName: "Semester 7/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Network monitoring, configuration management, and performance optimization</p>",
    CourseGroupID: "17577",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 15,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "504004",
        SubjectName: "Network Security",
      },
    ],
  },
  {
    LectureHours: 2,
    PracticeHours: 2,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504008",
    Semester: 7,
    AcademicYear: 2024,
    ProgramSemester: 7,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Cloud Computing",
    SubjectName_EN: "Cloud Computing",
    TotalCredits: 4,
    LectureCredits: 2,
    PracticeCredits: 2,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17578,
    TrainingMajorCode: "ELECTIVE",
    CourseTypeColorBackground: "#FFF3E0",
    CourseTypeColorFont: "#F57C00",
    CourseTypeName: "B.2     Major Elective Subjects",
    CourseTypeName_EN: "B.2     Major Elective Subjects",
    SemesterName: "Semester 7/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Cloud architectures, virtualization, containerization, and cloud services</p>",
    CourseGroupID: "17578",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 4,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 1,
    PracticeHoursCount: 30,
    LectureHoursCount: 30,
    SelfStudyHoursCount: 60,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 0,
    PracticeHours: 6,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504009",
    Semester: 7,
    AcademicYear: 2024,
    ProgramSemester: 7,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Capstone Project I",
    SubjectName_EN: "Capstone Project I",
    TotalCredits: 6,
    LectureCredits: 0,
    PracticeCredits: 6,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17579,
    TrainingMajorCode: "PROJECT",
    CourseTypeColorBackground: "#E8F5E8",
    CourseTypeColorFont: "#2E7D32",
    CourseTypeName: "C.1     Capstone Project",
    CourseTypeName_EN: "C.1     Capstone Project",
    SemesterName: "Semester 7/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Independent research and development project in computer networks</p>",
    CourseGroupID: "17579",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 90,
    LectureHoursCount: 0,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  // Semester 8 - Final Semester
  {
    LectureHours: 0,
    PracticeHours: 8,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504010",
    Semester: 8,
    AcademicYear: 2024,
    ProgramSemester: 8,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Capstone Project II",
    SubjectName_EN: "Capstone Project II",
    TotalCredits: 8,
    LectureCredits: 0,
    PracticeCredits: 8,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip:
      "<div id='tooltip-504010' class='tooltip_description' style='display:none' title='Prerequisite Subjects'>Previous Subject:<br/> - Capstone Project I (504009)<br/></div>",
    PrerequisiteType: 1,
    HasPrerequisite: true,
    TotalPrerequisiteTypes: 1,
    CourseTypeID: 17579,
    TrainingMajorCode: "PROJECT",
    CourseTypeColorBackground: "#E8F5E8",
    CourseTypeColorFont: "#2E7D32",
    CourseTypeName: "C.1     Capstone Project",
    CourseTypeName_EN: "C.1     Capstone Project",
    SemesterName: "Semester 8/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Completion and presentation of the capstone project</p>",
    CourseGroupID: "17579",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 120,
    LectureHoursCount: 0,
    SelfStudyHoursCount: 120,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [
      {
        SubjectID: "504009",
        SubjectName: "Capstone Project I",
      },
    ],
  },
  {
    LectureHours: 0,
    PracticeHours: 3,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504011",
    Semester: 8,
    AcademicYear: 2024,
    ProgramSemester: 8,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Professional Internship",
    SubjectName_EN: "Professional Internship",
    TotalCredits: 3,
    LectureCredits: 0,
    PracticeCredits: 3,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17580,
    TrainingMajorCode: "INTERNSHIP",
    CourseTypeColorBackground: "#F3E5F5",
    CourseTypeColorFont: "#7B1FA2",
    CourseTypeName: "D.1     Professional Practice",
    CourseTypeName_EN: "D.1     Professional Practice",
    SemesterName: "Semester 8/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Practical work experience in computer networks industry</p>",
    CourseGroupID: "17580",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 45,
    LectureHoursCount: 0,
    SelfStudyHoursCount: 45,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
  {
    LectureHours: 3,
    PracticeHours: 0,
    EducationProgramID: "0",
    MajorID: "504",
    SubjectID: "504012",
    Semester: 8,
    AcademicYear: 2024,
    ProgramSemester: 8,
    IsRequired: true,
    AcademicYearID: 2024,
    SubjectName: "Network Ethics and Law",
    SubjectName_EN: "Network Ethics and Law",
    TotalCredits: 3,
    LectureCredits: 3,
    PracticeCredits: 0,
    SelfStudyCredits: 0,
    InitialStatus: -1,
    SubjectDetailInfo: "",
    SubjectTooltip: "",
    PrerequisiteType: 0,
    HasPrerequisite: false,
    TotalPrerequisiteTypes: 0,
    CourseTypeID: 17581,
    TrainingMajorCode: "GENERAL",
    CourseTypeColorBackground: null,
    CourseTypeColorFont: null,
    CourseTypeName: "A.2     Professional Ethics",
    CourseTypeName_EN: "A.2     Professional Ethics",
    SemesterName: "Semester 8/2024-2025",
    IsSummerSemester: false,
    AUN_Info: "<p>Ethical considerations and legal aspects in computer networks and cybersecurity</p>",
    CourseGroupID: "17581",
    Notes: null,
    AccumulatedCredits: 0,
    GPAAccumulated: 0,
    BachelorCredits: 0,
    EngineerCredits: 0,
    IsPartOfNonBachelorGroup: false,
    IsExcludedFromEngineerProgram: false,
    HasEngineerGroup: false,
    MappedCourseGroupID: null,
    ElectiveCredits: 0,
    MappedCourseGroupName: null,
    MappedCourseGroupName_EN: null,
    IsMapped: 0,
    ParentCourseGroupID: null,
    IsRequiredElective: 0,
    PracticeHoursCount: 0,
    LectureHoursCount: 45,
    SelfStudyHoursCount: 90,
    IsCountedForGPA: true,
    IsCountedForCredits: true,
    PrerequisiteSubjects: [],
  },
];
